# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': '校区'},
        ),
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(to='repository.Menus'),
        ),
    ]
